-- MySQL Script generated by MySQL Workbench
-- Fri Feb 10 11:40:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- -----------------------------------------------------
-- Schema zfm1-zlanciaje_1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zfm1-zlanciaje_1` DEFAULT CHARACTER SET utf8 ;
USE `zfm1-zlanciaje_1` ;

-- -----------------------------------------------------
-- Table `zfm1-zlanciaje_1`.`Salle_sal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zfm1-zlanciaje_1`.`Salle_sal` (
  `sal_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sal_nom` VARCHAR(60) NOT NULL,
  `sal_adresse` VARCHAR(200) NOT NULL,
  `sal_capacite` INT NOT NULL,
  `sal_gestion` VARCHAR(50) NULL,
  `sal_asso` VARCHAR(50) NULL,
  `sal_president` VARCHAR(50) NULL,
  PRIMARY KEY (`sal_id`),
  UNIQUE INDEX `sal_id_UNIQUE` (`sal_id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zfm1-zlanciaje_1`.`Soiree_soi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zfm1-zlanciaje_1`.`Soiree_soi` (
  `soi_id` INT NOT NULL AUTO_INCREMENT,
  `soi_nom` VARCHAR(50) NOT NULL,
  `sal_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`soi_id`),
  UNIQUE INDEX `soi_id_UNIQUE` (`soi_id` ASC) ,
  INDEX `fk_Soiree_soi_Salle_sal_idx` (`sal_id` ASC) ,
  CONSTRAINT `fk_Soiree_soi_Salle_sal`
    FOREIGN KEY (`sal_id`)
    REFERENCES `zfm1-zlanciaje_1`.`Salle_sal` (`sal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zfm1-zlanciaje_1`.`Groupe_grp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zfm1-zlanciaje_1`.`Groupe_grp` (
  `grp_id` INT NOT NULL AUTO_INCREMENT,
  `grp_nom` VARCHAR(50) NULL,
  PRIMARY KEY (`grp_id`),
  UNIQUE INDEX `grp_id_UNIQUE` (`grp_id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zfm1-zlanciaje_1`.`Concert_con`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zfm1-zlanciaje_1`.`Concert_con` (
  `con_id` INT NOT NULL AUTO_INCREMENT,
  `con_debut` DATETIME NULL,
  `con_fin` DATETIME NULL,
  `soi_id` INT NOT NULL,
  `grp_id` INT NOT NULL,
  PRIMARY KEY (`con_id`),
  UNIQUE INDEX `con_id_UNIQUE` (`con_id` ASC) ,
  INDEX `fk_Concert_con_Soiree_soi1_idx` (`soi_id` ASC) ,
  INDEX `fk_Concert_con_Groupe_grp1_idx` (`grp_id` ASC) ,
  CONSTRAINT `fk_Concert_con_Soiree_soi1`
    FOREIGN KEY (`soi_id`)
    REFERENCES `zfm1-zlanciaje_1`.`Soiree_soi` (`soi_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Concert_con_Groupe_grp1`
    FOREIGN KEY (`grp_id`)
    REFERENCES `zfm1-zlanciaje_1`.`Groupe_grp` (`grp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zfm1-zlanciaje_1`.`Artiste_art`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zfm1-zlanciaje_1`.`Artiste_art` (
  `art_id` INT NOT NULL AUTO_INCREMENT,
  `art_nom` VARCHAR(50) NOT NULL,
  `art_prenom` VARCHAR(50) NOT NULL,
  `art_pseudo` VARCHAR(50) NOT NULL,
  `art_ville` VARCHAR(50) NOT NULL,
  `art_age` INT NOT NULL,
  `grp_id` INT NOT NULL,
  PRIMARY KEY (`art_id`),
  UNIQUE INDEX `art_id_UNIQUE` (`art_id` ASC) ,
  INDEX `fk_Artiste_art_Groupe_grp1_idx` (`grp_id` ASC) ,
  CONSTRAINT `fk_Artiste_art_Groupe_grp1`
    FOREIGN KEY (`grp_id`)
    REFERENCES `zfm1-zlanciaje_1`.`Groupe_grp` (`grp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `zfm1-zlanciaje_1`.`Billet_bil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zfm1-zlanciaje_1`.`Billet_bil` (
  `bil_id` INT NOT NULL AUTO_INCREMENT,
  `bil_nom` VARCHAR(50) NOT NULL,
  `bil_prenom` VARCHAR(50) NOT NULL,
  `Billet_bilcol` VARCHAR(45) NULL,
  `soi_id` INT NULL,
  PRIMARY KEY (`bil_id`),
  UNIQUE INDEX `bil_id_UNIQUE` (`bil_id` ASC) ,
  INDEX `fk_Billet_bil_Soiree_soi1_idx` (`soi_id` ASC) ,
  CONSTRAINT `fk_Billet_bil_Soiree_soi1`
    FOREIGN KEY (`soi_id`)
    REFERENCES `zfm1-zlanciaje_1`.`Soiree_soi` (`soi_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zfm1-zlanciaje_1`.`Compte_cpt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zfm1-zlanciaje_1`.`Compte_cpt` (
  `cpt_pseudo` VARCHAR(50) NOT NULL,
  `cpt_mdp` VARCHAR(256) NULL,
  PRIMARY KEY (`cpt_pseudo`),
  UNIQUE INDEX `cpt_pseudo_UNIQUE` (`cpt_pseudo` ASC) )
ENGINE = InnoDB;